name: Code Coverage

on: 
  workflow_run:
    workflows: [Java CI with Maven]
    types: [completed]

jobs:
  code-coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Get the Coverage info
      run: |
        echo "Total coverage coverage-overall ${{ steps.jacoco.outputs.coverage-overall }}"
        echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"
        echo "Coverage coveragePercentage ${{ steps.jacoco_reporter.outputs.coveragePercentage }}"
        echo "Coverage coveragePercentageString ${{ steps.jacoco_reporter.outputs.coveragePercentageString }}"
    - name: Fail PR if coverage is less than 80%
      if: ${{ steps.jacoco.outputs.coverage-overall < 80.0 || steps.jacoco.outputs.coverage-changed-files < 80.0 }}
      uses: actions/github-script@v6
      with:
         script: |
            core.setFailed('Code coverage is less than 80%!')
