# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches-ignore: [ main ]


jobs:
  build:

    runs-on: ubuntu-latest

    outputs:
      coverage_overall: ${{ steps.coverage-output.outputs.coverage_overall }}
      coverage_changed_files: ${{ steps.coverage-output.outputs.coverage_changed_files }}
      coverageSummary: ${{ steps.coverage-output.outputs.coverageSummary }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'corretto'
          cache: maven
      - name: Build with Maven
        run: mvn clean install --file pom.xml
      - name: JaCoCo Code Coverage Report
        id: jacoco_reporter
        uses: PavanMudigonda/jacoco-reporter@v4.8
        with:
          coverage_results_path: coverage/target/site/jacoco-aggregate/jacoco.xml
          coverage_report_name: Coverage
          coverage_report_title: Coverage Report
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_check_run: false
          minimum_coverage: 80
          fail_below_threshold: true
          publish_only_summary: true
      - name: Jacoco Report to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: coverage/target/site/jacoco-aggregate/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 80
          min-coverage-changed-files: 80
          debug-mode: true
          continue-on-error: true
          title: Coverage Summary

      - name: Set Coverage Output
        id: coverage-output
        run: |
          echo "coverage_overall=${{ steps.jacoco.outputs.coverage-overall }}" >> "$GITHUB_OUTPUT"
          echo "coverage_changed_files=${{ steps.jacoco.outputs.coverage-changed-files }}" >> "$GITHUB_OUTPUT"
          echo "coverageSummary=${{ steps.jacoco_reporter.outputs.coverageSummary }}" >> $GITHUB_OUTPUT

      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

  Code-Coverage-Changed-Files:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Publish Coverage Workflow Build Summary
        run: echo ${{ needs.build.outputs.coverageSummary }} >> $GITHUB_STEP_SUMMARY

      - name: Get the Coverage info
        run: |
          echo "Total coverage = ${{ needs.build.outputs.coverage_overall }}"
          echo "Changed Files coverage = ${{ needs.build.outputs.coverage_changed_files }}"

      - name: Fail PR if coverage is less than 80%
        if: ${{ needs.build.outputs.coverage_changed_files < 80.0 }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('Code coverage is less than 80%!')
